### ISSUE TITLE
Update the readme and add documentation

### ISSUE THREAD

**Issue by lukecampbell** [ioos/qartod#8]
I was hoping I could dump the sphinx generated website which I used for documentation. I'll see about getting the documentation hosted somewhere. In the meantime I can update the readme to have some more detailed information about the project.

**Comment by emiliom** [comment]
@lukecampbell, having *some* documentation would be great ... I would also suggest that if you could compile one or two of the presentations you've already given, that demonstrated the use of the code, that would be a helpful documentation that's hopefully easy to add -- either as a file dump or simply a link on the README file to wherever the presentation files exist. Thanks.

**Comment by emiliom** [comment]
@lukecampbell, how is the documentation that was mentioned at the QARTOD DMAC call on Monday coming along? Pinging @tslawecki, to keep him in the loop.

**Comment by lukecampbell** [comment]
@benjwadams is wrapping up the documentation using sphinx as I type this. Hopefully tomorrow.

**Comment by emiliom** [comment]
Great, thanks!

**Comment by flbahr** [comment]
Luke, have been testing qc.py using anaconda in a iPython notebook and had some problems with type mismatches using the rate_of_change_check.  My time variable was in an numpy array of numbers as seconds since Jan 1 1970.  I could not use as is but computed a diff of the values and then typed the the result as 'timedelta64[s]' .  If I didn't do this I got errors about ufunc not able to do the division due to wrong types.  The type of numpy.timedelta(1,'s')/quantities.second is on my machine '<m8[s]'.  
I'm not using panda data frames.

**Comment by lukecampbell** [comment]
http://ioos.github.io/qartod/

**Comment by lukecampbell** [comment]
@flbahr could you put that in another issue?

**Comment by emiliom** [comment]
@lukecampbell and @benjwadams: thanks so much for putting together the documentation! Looks good.

**Comment by emiliom** [comment]
Actually, I have two small comments about https://github.com/ioos/qartod/blob/master/README.rst:
- It has some syntax problems, that look like Markdown while this is an rst file (I'm not familiar with rst syntax)
- Add a prominent link to the new documentation page, http://ioos.github.io/qartod/

**Comment by lukecampbell** [comment]
Done.

**Comment by emiliom** [comment]
Looks good, thanks!

**Comment by emiliom** [comment]
Looks like this issue can be closed
